// 1. SETUP
const express = require('express'); // importing express
const hbs = require('hbs');
const app = express(); // create a new express application

// register hbs as the template engine (aka 'view engine')
app.set('view engine', 'hbs');

// enable static files
// static files -> content not generated by programming
// express.static(): tells Express we want to use static files
//  - first parameter: which directory/folder relative to index.js it will be in
app.use(express.static('public'));

// 2. ROUTES
app.get('/', function(req, res){
    res.send("Hello");
})

// route parameters 
// i.e placeholders
// the URL below contains one PARAMETER (or param) for short
// the KEY of the parameter is :<key_name>
app.get('/hello/:userName', function(req,res){
    // req.params is an object that stores
    // the key and value of each parameter
    console.log(req.params);
    res.send("Hello, " + req.params.userName);
})

app.get('/add/:num1/:num2', function(req,res){
    console.log(req.params);
    const n1 = parseInt(req.params.num1);
    const n2 = parseInt(req.params.num2);
    const sum = n1 + n2;
    res.send("Sum is " + sum);
})

app.get('/contact-us', function(req,res){
    // res.render is the same as res.send,
    // excpet it will send the content of a template file (contact-form.hbs)
    
    // note: all hbs files are in the views folder (by design of Express)
    res.render('contact-form.hbs');
});

app.get('/luckynumber', function(req,res){
    // we can send variables to HBS files
    const luckyNumber = Math.floor(Math.random() * 9999 + 1000);
   // the two second parameter to `render` is a
   // an object. The key will be variables for the hbs file
    res.render('lucky.hbs',{
        "number": luckyNumber,
        "date": new Date()
    })
})

// 3. STARTING THE SERVER
app.listen(3002, function(){
    console.log("Server has started")
})